options:
  tools:
    type: string
    default: git gcc make bzr
    description: Tooling to deploy alongside jenkins
  release:
    type: string
    default: lts
    description: |
     Source of Jenkins, options include:
     - lts: use the most recent Jenkins LTS release.
     - trunk: use the most recent Jenkins release.
     - bundle: use a bundled deb package.
     - http(s)://...: http(s) link to a retrievable jenkins deb
  username:
    type: string
    default: admin
    description: Admin user username - used to manage
      slave nodes so please don't change in Jenkins.
  password:
    type: string
    default: ""
    description: Admin user password - used to manage
      slave nodes so please don't change in Jenkins.
  plugins:
    type: string
    default: ""
    description: Space separated list of plugins to install
  plugins-site:
    type: string
    default: "https://updates.jenkins-ci.org/latest/"
    description: Site to download plugin .hpi files from.
  plugins-check-certificate:
    type: string
    default: "yes"
    description: Set to no to allow downloading from an invalid https site.
  remove-unlisted-plugins:
    type: string
    default: "no"
    description: |
      Set this to yes to remove any plugins not listed in plugins
      from the installation.
